#kind: pipeline
#name: pull

#steps:
#  - name: pull
#    image: plugins/docker
#    commands:
#      - docker login 

kind: pipeline
name: pull

steps:
  - name: pull
    image: plugins/git
    commands:
      - git pull origin main
